### ISSUE TITLE
the directory "data/preprocessed" needs to be manually created.

### ISSUE THREAD

**Issue by zhiyumeng** [stangelid/oposum#1]
the directory "data/preprocessed" needs to be manually created.
Traceback (most recent call last):
  File "./scripts/prep_hier_hdf5.py", line 373, in <module>
    main()
  File "./scripts/prep_hier_hdf5.py", line 267, in main
    with open(args.name + '_word_mapping.txt', 'w') as f:
IOError: [Errno 2] No such file or directory: './data/preprocessed/BAGS_AND_CASES_MILNET_word_mapping.txt'

**Comment by fangguo1** [comment]
Hi, I met the same issue, do you have a solution right now? Thanks!

**Comment by zhiyumeng** [comment]
maybe you can create the directory manually (without editing the codes).

**Comment by fangguo1** [comment]
Did you finally make the model run successfully?

**Comment by fangguo1** [comment]
Did you finally make the model run successfully?

**Comment by zhiyumeng** [comment]
yes, I run the model successfully, but didn't train or test it. I just run the code, then stopped it after several seconds.

**Comment by KhanJr** [comment]
@zhiyumeng Hello sir i am very much interested to know how to add manually prepossessed folder in the directory, where to get /BAGS_AND_CASES_MILNET_word_mapping.txt this file ?

**Comment by zhiyumeng** [comment]
It has been a long time. I forget it. “the directory "data/preprocessed" needs to be manually created” is just the reason the code/scripts failed,so I created athe dolder，then re run the codes.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rizwan Khan<mailto:notifications@github.com>
发送时间: 2020年8月7日 23:51
收件人: stangelid/oposum<mailto:oposum@noreply.github.com>
抄送: fyyc<mailto:zhiyumengxiang@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [stangelid/oposum] the directory "data/preprocessed" needs to be manually created. (#1)


@zhiyumeng<https://github.com/zhiyumeng> Hello sir i am very much interested to know how to add manually prepossessed folder in the directory, where to get /BAGS_AND_CASES_MILNET_word_mapping.txt this file ?

―
